### ISSUE TITLE
STM32duino

### ISSUE THREAD

**Issue by koendv** [odo2063/stm32duino_for_raspi#1]
Hi. I suppose this is the hardware you use for your STM32 Arduino? 

I'm looking at stm32duino on raspberry, but would need some additional info. 
On the intel linux you use for arduino development, could you do the following:
- exit Arduino IDE, if running
- mv .arduino15 .arduino15.OLD (save current arduino environment)
- start Arduino IDE
- Go to Board manager, install stm32duino
- exit arduino IDE
- make tar or zip of .arduino15 directory, somehow let me download tar or zip.
-  mv .arduino15 .arduino15.NEW
- mv .arduino15.OLD .arduino15 (restore old arduino environment).

Roughly speaking, I'm after the following information: what files are installed for stm32duino support on intel linux? Then I can try to replace these files with the arm equivalent, and see what happens.

Thanks.

koen

**Comment by odo2063** [comment]
I don't like the non PM policy too...

**Comment by koendv** [comment]
OK. First attempt. Please try this:

https://github.com/koendv/stm32duino-raspberrypi/releases/download/v1.3.1-0/arduino15-raspberrybuster.zip

Install in raspberry instead of the current .arduino15  directory. 

Check with eg. ldd .arduino15/packages/STM32/tools/STM32Tools/1.3.1/tools/linux64/dfu-util/dfu-util 
whether you need to install libusb-1.0.0-dev.

Compiling works.

**Comment by koendv** [comment]
I've written down step-by-step instructions on how to install stm32duino on raspberry pi. 
https://github.com/koendv/stm32duino-raspberrypi
Can you try them and give some feedback?

thanks.

**Comment by odo2063** [comment]
got some error while compiling standard/empty Sketch...

```
/home/pi/.arduino15/packages/STM32/tools/arm-none-eabi-gcc/8.2.1-1.7/bin/arm-none-eabi-gcc-ar rcs /tmp/arduino_build_938417/core/core.a /tmp/arduino_build_938417/core/stm32/startup_stm32yyxx.S.o
/home/pi/.arduino15/packages/STM32/tools/arm-none-eabi-gcc/9.2.1-1.1/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ar: error while loading shared libraries: libfl.so.2: cannot open shared object file: No such file or directory
exit status 127
```

**Comment by koendv** [comment]
OK.   Let's walk through finding the problem: 
```
koen@raspberrypi:~ $ ls .arduino15/packages/STM32/tools/arm-none-eabi-gcc/9.2.1-1.1/arm-none-eabi/bin/ar
.arduino15/packages/STM32/tools/arm-none-eabi-gcc/9.2.1-1.1/arm-none-eabi/bin/ar
```
What are the shared libraries ar needs?
```
koen@raspberrypi:~ $ ldd .arduino15/packages/STM32/tools/arm-none-eabi-gcc/9.2.1-1.1/arm-none-eabi/bin/ar
	linux-vdso.so.1 (0xbe862000)
	/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so => /usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so (0xb6f80000)
	libfl.so.2 => /usr/lib/arm-linux-gnueabihf/libfl.so.2 (0xb6f1a000)
	libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0xb6f07000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb6db9000)
	libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0xb6d37000)
	/lib/ld-linux-armhf.so.3 (0xb6f95000)
```
You see libfl2.so.2 is needed by ar. On your system this file is probably missing.
What package provides libfl.so.2 ?
```
koen@raspberrypi:~ $ dpkg -S /usr/lib/arm-linux-gnueabihf/libfl.so.2
libfl2:armhf: /usr/lib/arm-linux-gnueabihf/libfl.so.2
```
The package is called libfl2:
```
koen@raspberrypi:~ $ apt-cache search libfl2
libfl2 - SHARED library for flex (a fast lexical analyzer generator)
koen@raspberrypi:~ $ 
```
This means flex is missing on your system. So I'd try 
```
apt-get install flex 
``` 
or
``` 
apt-get install libfl2
```

For completeness: when building the toolchain, I used the following two commands:
```
apt-get -f install -y build-essential autoconf autogen bison dejagnu flex flip gawk git gperf gzip nsis openssh-client p7zip-full perl python-dev libisl-dev scons tcl texinfo tofrodos wget zip texlive texlive-plain-generic texlive-extra-utils libncurses5-dev
apt-get install pkg-config libusb-1.0-0-dev
```
so anything missing on your system will probably be one of these.

rgrds,

koen

**Comment by odo2063** [comment]
so for later when there is a "just download it"-package those things should be added/mentioned somewhere...

compiles with flex installed. Which pulls libfl-dev and libfl12.

**Comment by koendv** [comment]
OK. Good news. Added to README.md.
Does uploading work?
(Suggest first test with a device on your desk - not something in the middle of the North Sea ;)
